//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeBook.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePosition
    {
        public System.Guid ID { get; private set; }
        public System.Guid EmployeeID { get; set; }
        public System.Guid PositionID { get; set; }
        public System.DateTime AssignmentDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Position Position { get; set; }
    }
}
