//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeBook.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PositionSkill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PositionSkill()
        {
            this.EmployeePositionSkills = new HashSet<EmployeePositionSkill>();
        }
    
        public System.Guid ID { get; private set; }
        public System.Guid PositionID { get; set; }
        public System.Guid SkillID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeePositionSkill> EmployeePositionSkills { get; set; }
        public virtual Position Position { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
